// Universe screener: LQ45 + sejumlah mid-cap likuid IDX.
// Diperluas dari 15 blue-chip agar lebih banyak emiten berkesempatan lolos
// kriteria BSJP/BPJS (bukan hanya saham besar). Catatan: makin banyak simbol
// makin berat fetch ke Yahoo Finance — fetchManyDailyOhlcv membatasi konkurensi
// dan men-skip simbol yang gagal agar pipeline tetap jalan.
export const IDX_WATCHLIST = [
  // Banking & finance
  "BBCA",
  "BBRI",
  "BMRI",
  "BBNI",
  "BRIS",
  "BBTN",
  "ARTO",
  "BTPS",
  "AGRO",
  // Telco, media & tech
  "TLKM",
  "EXCL",
  "ISAT",
  "TOWR",
  "MTEL",
  "TBIG",
  "GOTO",
  "BUKA",
  "EMTK",
  "MNCN",
  "SCMA",
  // Consumer & retail
  "UNVR",
  "ICBP",
  "INDF",
  "MYOR",
  "KLBF",
  "SIDO",
  "AMRT",
  "MAPI",
  "MAPA",
  "ACES",
  "ERAA",
  "CPIN",
  "JPFA",
  "HMSP",
  "GGRM",
  "ULTJ",
  "KAEF",
  "HEAL",
  "MIKA",
  "RALS",
  // Energy
  "ADRO",
  "PGAS",
  "PTBA",
  "ITMG",
  "MEDC",
  "AKRA",
  "HRUM",
  "INDY",
  "ELSA",
  // Metals & mining
  "ANTM",
  "MDKA",
  "INCO",
  "TINS",
  "NCKL",
  "BRMS",
  "MBMA",
  "PSAB",
  "HRTA",
  // Property & construction
  "BSDE",
  "CTRA",
  "PWON",
  "SMRA",
  "PTPP",
  "WIKA",
  "ADHI",
  // Industrials & auto
  "ASII",
  "UNTR",
  "AUTO",
  "GJTL",
  // Basic materials
  "SMGR",
  "INTP",
  "BRPT",
  "TPIA",
  "TKIM",
  "INKP",
  "ESSA",
  // Infra & agri
  "JSMR",
  "AALI",
  "LSIP",
  "TAPG",
] as const;
